export const searchBarStyles = {
  searchContainer: {
    position: "relative",
  },
  inputContainer: {
    border: "1px solid #d2d2d2",
    borderRadius: "4px",
    display: "flex",
    flexWrap: "wrap",
    background: "#fff",
  },
  inputField: {
    height: "35px",
    border: "none",
    outline: "none",
    borderRadius: "6px",
    minWidth: "250px",
    padding: "5px 8px",
    flexGrow: "100",
  },
  close: {
    fontWeight: "bold",
    display: "inline-block",
    transform: "scale(1.4)",
    marginLeft: "0.75em",
    fontSize: "8px",
  },
  tag: {
    fontSize: "13px",
    padding: "6px 10px",
    margin: "0.25em 0.1em",
    display: "inline-flex",
    backgroundColor: "#eee",
    transition: "all 0.1s linear",
    cursor: "pointer",
  },
  dropDownContainer: {
    position: "absolute",
    zIndex: "999",
    background: "white",
    width: "100%",
    border: "1px solid #d2d2d2",
  },
  leftRightColumn: {
    display: "flex",
    borderBottom: "1px solid #d2d2d2",
  },
  leftColumn: {
    width: "25%",
    display: "flex",
    borderRight: "1px solid #d2d2d2",
    alignItems: "center",
    justifyContent: "center",
    padding: "8px",
  },
  rightColumn: {
    width: "75%",
    padding: "5px",
    overflowWrap: "break-word",
    maxHeight: "150px",
    overflowY: "auto",
    overflowX: "hidden",
    "& .column-list:last-child": {
      borderBottom: "none",
    },
  },
  columnList: {
    padding: "5px",
    cursor: "pointer",
    background: "#f1f1f1",
    margin: "2px",
    lineHeight: "30px",
  },
};
